// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Entity struct {
	Name       string      `json:"name"`
	EntityType string      `json:"entity_type"`
	Embedding  interface{} `json:"embedding"`
	Metadata   string      `json:"metadata"`
	CreatedAt  int64       `json:"created_at"`
	UpdatedAt  int64       `json:"updated_at"`
}

type EntityFileRelation struct {
	ID              int64   `json:"id"`
	EntityName      string  `json:"entity_name"`
	FileID          string  `json:"file_id"`
	RelationType    string  `json:"relation_type"`
	Confidence      float64 `json:"confidence"`
	SimilarityScore float64 `json:"similarity_score"`
	Metadata        string  `json:"metadata"`
	CreatedAt       int64   `json:"created_at"`
}

type File struct {
	ID          string       `json:"id"`
	WorkspaceID string       `json:"workspace_id"`
	FilePath    string       `json:"file_path"`
	Size        int64        `json:"size"`
	ModTime     int64        `json:"mod_time"`
	IsDir       sql.NullBool `json:"is_dir"`
	Checksum    string       `json:"checksum"`
	Embedding   interface{}  `json:"embedding"`
	Metadata    string       `json:"metadata"`
	CreatedAt   int64        `json:"created_at"`
	UpdatedAt   int64        `json:"updated_at"`
}

type Observation struct {
	ID         int64       `json:"id"`
	EntityName string      `json:"entity_name"`
	Content    string      `json:"content"`
	Embedding  interface{} `json:"embedding"`
	CreatedAt  int64       `json:"created_at"`
}

type OperationHistory struct {
	ID            string `json:"id"`
	WorkspaceID   string `json:"workspace_id"`
	OperationType string `json:"operation_type"`
	EntityPath    string `json:"entity_path"`
	OldPath       string `json:"old_path"`
	NewPath       string `json:"new_path"`
	Metadata      string `json:"metadata"`
	PerformedBy   string `json:"performed_by"`
	PerformedAt   int64  `json:"performed_at"`
}

type Snapshot struct {
	ID             string `json:"id"`
	WorkspaceID    string `json:"workspace_id"`
	TakenAt        int64  `json:"taken_at"`
	DirectoryState []byte `json:"directory_state"`
	Description    string `json:"description"`
	CreatedAt      int64  `json:"created_at"`
}

type Workspace struct {
	ID        string `json:"id"`
	RootPath  string `json:"root_path"`
	Config    string `json:"config"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}
