// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"
)

type Querier interface {
	// Batch insert multiple entities
	BatchCreateEntities(ctx context.Context, arg BatchCreateEntitiesParams) error
	// Batch create multiple entity-file relationships
	BatchCreateEntityFileRelations(ctx context.Context, arg BatchCreateEntityFileRelationsParams) error
	// Batch insert multiple files
	BatchCreateFiles(ctx context.Context, arg BatchCreateFilesParams) error
	// Batch create multiple observations
	BatchCreateObservations(ctx context.Context, arg BatchCreateObservationsParams) error
	// Batch create multiple operation records
	BatchCreateOperations(ctx context.Context, arg BatchCreateOperationsParams) error
	// Batch create multiple workspaces
	BatchCreateWorkspaces(ctx context.Context, arg BatchCreateWorkspacesParams) error
	// Batch delete multiple entities
	BatchDeleteEntities(ctx context.Context, name string) error
	// Batch delete multiple files
	BatchDeleteFiles(ctx context.Context, id string) error
	// Batch delete multiple observations
	BatchDeleteObservations(ctx context.Context, id int64) error
	// Batch update multiple entities
	BatchUpdateEntities(ctx context.Context, arg BatchUpdateEntitiesParams) error
	// Batch update multiple files
	BatchUpdateFiles(ctx context.Context, arg BatchUpdateFilesParams) error
	// Batch update multiple observations
	BatchUpdateObservations(ctx context.Context, arg BatchUpdateObservationsParams) error
	// Batch update confidence scores
	BatchUpdateRelationConfidence(ctx context.Context, arg BatchUpdateRelationConfidenceParams) error
	// Batch update workspace configurations
	BatchUpdateWorkspaceConfigs(ctx context.Context, arg BatchUpdateWorkspaceConfigsParams) error
	// Bulk update embeddings for multiple files
	BulkUpdateFileEmbeddings(ctx context.Context, arg BulkUpdateFileEmbeddingsParams) error
	// Remove relationships below confidence threshold
	CleanupLowConfidenceRelations(ctx context.Context, confidence float64) error
	// Remove operations older than specified date
	CleanupOldOperations(ctx context.Context, performedAt int64) error
	// Create a new entity with upsert semantics
	CreateEntity(ctx context.Context, arg CreateEntityParams) (Entity, error)
	// Create a relationship between entity and file
	CreateEntityFileRelation(ctx context.Context, arg CreateEntityFileRelationParams) (EntityFileRelation, error)
	// Create a new file with upsert semantics
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	// Create a new observation for an entity
	CreateObservation(ctx context.Context, arg CreateObservationParams) (Observation, error)
	// Create a new operation history entry
	CreateOperation(ctx context.Context, arg CreateOperationParams) (OperationHistory, error)
	// Create a new snapshot for a workspace
	CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (Snapshot, error)
	// Create a new workspace
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	// Delete entity by name
	DeleteEntity(ctx context.Context, name string) error
	// Delete specific relationship
	DeleteEntityFileRelation(ctx context.Context, arg DeleteEntityFileRelationParams) error
	// Delete all observations for an entity
	DeleteEntityObservations(ctx context.Context, entityName string) error
	// Delete file by ID
	DeleteFile(ctx context.Context, id string) error
	// Delete observation by ID
	DeleteObservation(ctx context.Context, id int64) error
	// Delete snapshot by ID
	DeleteSnapshot(ctx context.Context, id string) error
	// Delete workspace by ID
	DeleteWorkspace(ctx context.Context, id string) error
	// Search entities by metadata content
	GetEntitiesByMetadata(ctx context.Context, arg GetEntitiesByMetadataParams) ([]Entity, error)
	// Get entities ordered by number of observations
	GetEntitiesByObservationCount(ctx context.Context, arg GetEntitiesByObservationCountParams) ([]GetEntitiesByObservationCountRow, error)
	// Get all entities of a specific type
	GetEntitiesByType(ctx context.Context, entityType string) ([]Entity, error)
	// Get entities that have embeddings for vector operations
	GetEntitiesWithEmbeddings(ctx context.Context, arg GetEntitiesWithEmbeddingsParams) ([]Entity, error)
	// Get entities with observation counts and relation counts using window functions
	GetEntitiesWithStats(ctx context.Context, arg GetEntitiesWithStatsParams) ([]GetEntitiesWithStatsRow, error)
	// Get entity by name
	GetEntity(ctx context.Context, name string) (Entity, error)
	// Get network of relationships for analysis using CTEs
	GetEntityFileNetwork(ctx context.Context, arg GetEntityFileNetworkParams) ([]GetEntityFileNetworkRow, error)
	// Get specific entity-file relationship
	GetEntityFileRelation(ctx context.Context, arg GetEntityFileRelationParams) (EntityFileRelation, error)
	// Get observation statistics for an entity
	GetEntityObservationStats(ctx context.Context, entityName string) (GetEntityObservationStatsRow, error)
	// Get all observations for an entity
	GetEntityObservations(ctx context.Context, entityName string) ([]Observation, error)
	// Get all relationships for an entity
	GetEntityRelations(ctx context.Context, entityName string) ([]GetEntityRelationsRow, error)
	// Get entity with its observations using CTE
	GetEntityWithObservations(ctx context.Context, arg GetEntityWithObservationsParams) (GetEntityWithObservationsRow, error)
	// Get file by ID
	GetFile(ctx context.Context, id string) (File, error)
	// Get file by workspace and path
	GetFileByPath(ctx context.Context, arg GetFileByPathParams) (File, error)
	// Get all relationships for a file
	GetFileRelations(ctx context.Context, fileID string) ([]GetFileRelationsRow, error)
	// Get file statistics for a workspace
	GetFileStatsByWorkspace(ctx context.Context, workspaceID string) (GetFileStatsByWorkspaceRow, error)
	// Get files within a size range
	GetFilesBySizeRange(ctx context.Context, arg GetFilesBySizeRangeParams) ([]File, error)
	// Get files related to entities of specific type
	GetFilesForEntityType(ctx context.Context, arg GetFilesForEntityTypeParams) ([]GetFilesForEntityTypeRow, error)
	// Get files that have embeddings (for semantic search)
	GetFilesWithEmbeddings(ctx context.Context, arg GetFilesWithEmbeddingsParams) ([]File, error)
	// Get files that need embedding generation
	GetFilesWithoutEmbeddings(ctx context.Context, arg GetFilesWithoutEmbeddingsParams) ([]GetFilesWithoutEmbeddingsRow, error)
	// Get relationships above confidence threshold
	GetHighConfidenceRelations(ctx context.Context, arg GetHighConfidenceRelationsParams) ([]EntityFileRelation, error)
	// Get the most recent snapshot for a workspace
	GetLatestSnapshot(ctx context.Context, workspaceID string) (Snapshot, error)
	// Get observation by ID
	GetObservation(ctx context.Context, id int64) (Observation, error)
	// Get observations for multiple entities
	GetObservationsByEntities(ctx context.Context, arg GetObservationsByEntitiesParams) ([]Observation, error)
	// Get observations within a time range
	GetObservationsByTimeRange(ctx context.Context, arg GetObservationsByTimeRangeParams) ([]Observation, error)
	// Get observations that have embeddings for vector search
	GetObservationsWithEmbeddings(ctx context.Context, arg GetObservationsWithEmbeddingsParams) ([]Observation, error)
	// Get operation by ID
	GetOperation(ctx context.Context, id string) (OperationHistory, error)
	// Get operation statistics for a workspace
	GetOperationStats(ctx context.Context, workspaceID string) (GetOperationStatsRow, error)
	// Get operation summary by type and user
	GetOperationSummary(ctx context.Context, workspaceID string) ([]GetOperationSummaryRow, error)
	// Get operations within a time range
	GetOperationsByTimeRange(ctx context.Context, arg GetOperationsByTimeRangeParams) ([]OperationHistory, error)
	// Get operations of a specific type
	GetOperationsByType(ctx context.Context, arg GetOperationsByTypeParams) ([]OperationHistory, error)
	// Get operations performed by a specific user
	GetOperationsByUser(ctx context.Context, arg GetOperationsByUserParams) ([]OperationHistory, error)
	// Find relations where entity or file no longer exists
	GetOrphanedRelations(ctx context.Context) ([]GetOrphanedRelationsRow, error)
	// Get recently created entities
	GetRecentEntities(ctx context.Context, arg GetRecentEntitiesParams) ([]Entity, error)
	// Get recent observations across all entities
	GetRecentObservations(ctx context.Context, arg GetRecentObservationsParams) ([]Observation, error)
	// Get recent operations across all workspaces
	GetRecentOperations(ctx context.Context, arg GetRecentOperationsParams) ([]OperationHistory, error)
	// Get files modified within a time range
	GetRecentlyModifiedFiles(ctx context.Context, arg GetRecentlyModifiedFilesParams) ([]File, error)
	// Get comprehensive statistics about entity-file relationships
	GetRelationStatistics(ctx context.Context) (GetRelationStatisticsRow, error)
	// Get relationships of specific type with pagination
	GetRelationsByType(ctx context.Context, arg GetRelationsByTypeParams) ([]GetRelationsByTypeRow, error)
	// Find entities similar to a file based on embeddings (placeholder for vector similarity)
	GetSimilarEntitiesForFile(ctx context.Context, limit int64) ([]GetSimilarEntitiesForFileRow, error)
	// Get snapshot by ID
	GetSnapshot(ctx context.Context, id string) (Snapshot, error)
	// Get files most related to an entity with ranking
	GetTopRelatedFiles(ctx context.Context, arg GetTopRelatedFilesParams) ([]GetTopRelatedFilesRow, error)
	// Get workspace by ID
	GetWorkspace(ctx context.Context, id string) (Workspace, error)
	// Get recent activity for a workspace using window functions
	GetWorkspaceActivity(ctx context.Context, arg GetWorkspaceActivityParams) ([]GetWorkspaceActivityRow, error)
	// Get workspace by root path
	GetWorkspaceByPath(ctx context.Context, rootPath string) (Workspace, error)
	// Get file type distribution and size statistics
	GetWorkspaceFileDistribution(ctx context.Context, workspaceID string) (GetWorkspaceFileDistributionRow, error)
	// Get operation history for a workspace
	GetWorkspaceOperations(ctx context.Context, arg GetWorkspaceOperationsParams) ([]OperationHistory, error)
	// Get all snapshots for a workspace
	GetWorkspaceSnapshots(ctx context.Context, workspaceID string) ([]Snapshot, error)
	// Get summary of all workspaces with their statistics
	GetWorkspaceSummary(ctx context.Context) ([]GetWorkspaceSummaryRow, error)
	// Get largest files in workspace
	GetWorkspaceTopFiles(ctx context.Context, arg GetWorkspaceTopFilesParams) ([]GetWorkspaceTopFilesRow, error)
	// Get workspace with comprehensive statistics using CTEs
	GetWorkspaceWithStats(ctx context.Context, arg GetWorkspaceWithStatsParams) (GetWorkspaceWithStatsRow, error)
	// Get workspaces ordered by recent activity
	GetWorkspacesByActivity(ctx context.Context, arg GetWorkspacesByActivityParams) ([]GetWorkspacesByActivityRow, error)
	// List entities with pagination and filtering
	ListEntities(ctx context.Context, arg ListEntitiesParams) ([]Entity, error)
	// List files in a specific directory path
	ListFilesByDirectory(ctx context.Context, arg ListFilesByDirectoryParams) ([]File, error)
	// List all files in a workspace with pagination
	ListFilesByWorkspace(ctx context.Context, arg ListFilesByWorkspaceParams) ([]File, error)
	// List all workspaces with pagination
	ListWorkspaces(ctx context.Context, arg ListWorkspacesParams) ([]Workspace, error)
	// Basic text search in entity names and types
	SearchEntities(ctx context.Context, arg SearchEntitiesParams) ([]Entity, error)
	// Search entities by observation content
	SearchEntitiesByContent(ctx context.Context, arg SearchEntitiesByContentParams) ([]Entity, error)
	// Search entities by name
	SearchEntitiesByName(ctx context.Context, arg SearchEntitiesByNameParams) ([]Entity, error)
	// Search entities by type
	SearchEntitiesByType(ctx context.Context, arg SearchEntitiesByTypeParams) ([]Entity, error)
	// Search files by path or metadata content
	SearchFiles(ctx context.Context, arg SearchFilesParams) ([]File, error)
	// Search observations by content (basic LIKE search)
	SearchObservations(ctx context.Context, arg SearchObservationsParams) ([]Observation, error)
	// Search workspaces by root path
	SearchWorkspaces(ctx context.Context, arg SearchWorkspacesParams) ([]Workspace, error)
	// Update entity with optimistic locking
	UpdateEntity(ctx context.Context, arg UpdateEntityParams) (Entity, error)
	// Update relationship confidence and metadata
	UpdateEntityFileRelation(ctx context.Context, arg UpdateEntityFileRelationParams) (EntityFileRelation, error)
	// Update file metadata
	UpdateFile(ctx context.Context, arg UpdateFileParams) (File, error)
	// Update observation content and embedding
	UpdateObservation(ctx context.Context, arg UpdateObservationParams) (Observation, error)
	// Update workspace configuration
	UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error)
}

var _ Querier = (*Queries)(nil)
